---
name: install
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
jobs:
  install:
    runs-on: windows-latest
    steps:
      - name: Install Scoop
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
      - name: Add scoop to actions path
        run: Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
      - name: Scoop bucket add
        run: scoop bucket add utkuozdemir https://github.com/utkuozdemir/scoop-pv-migrate.git
      - name: Scoop install
        run: scoop install utkuozdemir/pv-migrate
      - name: Run command
        run: pv-migrate --version
